name: CI Go

on:
  push:
    branches: [ master, release-4.12, release-4.14, release-4.16, release-4.18 ]
  pull_request:
    branches: [ master, release-4.12, release-4.14, release-4.16, release-4.18 ]

jobs:
  integration-test:
    runs-on: ubuntu-latest
    env:
      MAKEFILE_PATH: Makefile.kni
      GOPATH: "/home/runner/go"
    steps:
      - name: Checkout sources
        uses: actions/checkout@v5 
        with:
          fetch-depth: 0

      - name: Set up golang
        uses: actions/setup-go@v6
        with:
          go-version: 1.24

      - name: Run integration test
        run:
          make -f ${MAKEFILE_PATH} integration-test-quick

  vendor-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Set up golang
        uses: actions/setup-go@v6
        with:
          go-version: 1.24

      - name: Verify vendoring
        run: ./hack-kni/verify-vendoring.sh
