name: CI Go

on:
  push:
    branches: [ master, release-4.12, release-4.14, release-4.16, release-4.18, release-4.20]
  pull_request:
    branches: [ master, release-4.12, release-4.14, release-4.16, release-4.18, release-4.20]

jobs:
  commit-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get branch names (pull request)
        shell: bash
        run: |
          echo "SOURCE_BRANCH_NAME=$(echo ${GITHUB_HEAD_REF} | tr / -)" >> $GITHUB_ENV
          echo "TARGET_BRANCH_NAME=$(echo ${GITHUB_BASE_REF} | tr / -)" >> $GITHUB_ENV

      - name: Debug
        run: |
          echo ${{ env.SOURCE_BRANCH_NAME }}
          echo ${{ env.TARGET_BRANCH_NAME }}

      - name: Verify commits
        run: |
          TRIGGER_BRANCH=${{ env.SOURCE_BRANCH_NAME }} \
          UPSTREAM_BRANCH=${{ env.TARGET_BRANCH_NAME }} \
          COMMITS=${{ github.event.pull_request.commits }} \
          ./hack-kni/verify-commits.sh

  integration-test:
    runs-on: ubuntu-latest
    env:
      MAKEFILE_PATH: Makefile.kni
      GOPATH: "/home/runner/go"
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up golang
        uses: actions/setup-go@v3
        with:
          go-version: 1.23

      - name: Run integration test
        run:
          make -f ${MAKEFILE_PATH} integration-test-quick

  vendor-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up golang
        uses: actions/setup-go@v3
        with:
          go-version: 1.23

      - name: Verify vendoring
        run: ./hack-kni/verify-vendoring.sh
